fieldLayouts:
  846f373e-a625-4557-93d9-ee5ffcab59a3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 0c6aca85-f362-4f39-bb4e-395748ddb935
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6bc056a0-a0b8-42c8-8cad-d7f0ac0f9ac5
        userCondition: null
fs: hardDisk
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: hardDisk
transformSubpath: ''
